### ISSUE TITLE
Typo in CLI Help

### ISSUE THREAD

**Issue by anmolsachan** [platform9/pf9ctl-cloud-providers#1]
`permissions` is currently written as `permisisons`

<img width="569" alt="Screenshot 2021-10-08 at 5 28 24 PM" src="https://user-images.githubusercontent.com/8753636/136553258-1771f6ad-39f3-4b0c-9ff8-5e7ab21ccf16.png">

**Comment by JasminDudicBloomteq** [comment]
Issue being closed as it was fixed in https://github.com/platform9/pf9ctl-cloud-providers/commit/c6c5e38600dacd89abb7fceb13472428dfba7cfd
