### ISSUE TITLE
Request for Feature- Make CLI installation success message green and failure red

### ISSUE THREAD

**Issue by anmolsachan** [platform9/pf9ctl-cloud-providers#2]
17:33:15:11 : Initializing: /Users/username/pf9
17:33:15:11 : Ensuring /Users/username/pf9/bin exists
17:33:15:11 : Ensuring /Users/username/pf9/db exists
17:33:15:11 : Ensuring /Users/username/pf9/log exists
17:33:15:11 : Ensuring /Users/username/pf9/log/cli_install.log exists
Note: SUDO access required to run Platform9 CLI.
      You might be prompted for your SUDO password.

Downloading Platform9 CLI binary...
Password:

Platform9 CLI binary downloaded.

Installing Platform9 CLI...

17:34:07:11 : Platform9 CLI installation completed successfully.

`Platform9 CLI installation completed successfully !`.  Should be green!

To start testing providers type:
        pf9cp help

**Comment by JasminDudicBloomteq** [comment]
Fixed in https://github.com/platform9/pf9ctl-cloud-providers/commit/40c14599b169130b05dc3189e8e1261614de2c44
